# Generated by Django 5.1.2 on 2024-10-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Danh mục')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=10, verbose_name='SĐT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=20, verbose_name='Tên tài khoản'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=20, verbose_name='Họ Tên'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Thời gian tạo')),
                ('ship_address', models.CharField(max_length=50, verbose_name='Địa chỉ nhận')),
                ('status', models.CharField(choices=[('incomplete', 'Chưa đặt'), ('doing', 'Đang thực hiện'), ('paid', 'Đã thanh toán'), ('done', 'Đã hoàn thành')], default='incomplete', max_length=10, verbose_name='Trạng thái')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tên hàng hóa')),
                ('price', models.IntegerField(verbose_name='Đơn giá')),
                ('unit', models.CharField(choices=[('p', '/cái'), ('g', '/gram'), ('kg', '/Kgram')], default='p', max_length=5, verbose_name='Đơn vị')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mô tả')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng')),
                ('categories', models.ManyToManyField(to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('price', models.IntegerField(verbose_name='Đơn giá')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='store.OrderProduct', to='store.product'),
        ),
    ]
