# Generated by Django 5.1.2 on 2024-10-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_user_phone_alter_user_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('p', '/cái'), ('g', '/gram'), ('kg', '/Kg')], default='p', max_length=5, verbose_name='Đơn vị'),
        ),
    ]
